In [27]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [28]:
df = pd.read_excel("../Myntra Raw Data.xlsx")
df.head()

Time (Mins)  Recall Rate
0            1         0.84
1            5         0.71
2           15         0.61
3           30         0.56
4           60         0.54

In [29]:
df.describe()

Time (Mins)  Recall Rate
count     13.000000    13.000000
mean    1679.307692     0.432308
std     3018.230508     0.222567
min        1.000000     0.080000
25%       30.000000     0.260000
50%      240.000000     0.450000
75%     1440.000000     0.560000
max    10080.000000     0.840000

In [30]:
df.kurt()

Time (Mins)    4.896013
Recall Rate   -0.572419
dtype: float64

In [31]:
df.skew()

Time (Mins)    2.257935
Recall Rate    0.143672
dtype: float64

In [33]:
df["Log of Time"] = np.log(df["Time (Mins)"])

In [34]:
df

Time (Mins)  Recall Rate  Log of Time
0             1         0.84     0.000000
1             5         0.71     1.609438
2            15         0.61     2.708050
3            30         0.56     3.401197
4            60         0.54     4.094345
5           120         0.47     4.787492
6           240         0.45     5.480639
7           480         0.38     6.173786
8           720         0.36     6.579251
9          1440         0.26     7.272398
10         2880         0.20     7.965546
11         5760         0.16     8.658693
12        10080         0.08     9.218309

In [35]:
df.describe()

Time (Mins)  Recall Rate  Log of Time
count     13.000000    13.000000    13.000000
mean    1679.307692     0.432308     5.226857
std     3018.230508     0.222567     2.794976
min        1.000000     0.080000     0.000000
25%       30.000000     0.260000     3.401197
50%      240.000000     0.450000     5.480639
75%     1440.000000     0.560000     7.272398
max    10080.000000     0.840000     9.218309

In [36]:
df.kurt()

Time (Mins)    4.896013
Recall Rate   -0.572419
Log of Time   -0.671292
dtype: float64

In [37]:
df.skew()

Time (Mins)    2.257935
Recall Rate    0.143672
Log of Time   -0.348620
dtype: float64

In [38]:
model = LinearRegression()

In [39]:
X = df[["Log of Time"]]

In [40]:
y = df[["Recall Rate"]]

In [41]:
X

Log of Time
0      0.000000
1      1.609438
2      2.708050
3      3.401197
4      4.094345
5      4.787492
6      5.480639
7      6.173786
8      6.579251
9      7.272398
10     7.965546
11     8.658693
12     9.218309

In [42]:
y

Recall Rate
0          0.84
1          0.71
2          0.61
3          0.56
4          0.54
5          0.47
6          0.45
7          0.38
8          0.36
9          0.26
10         0.20
11         0.16
12         0.08

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [53]:
model.fit(X_train,y_train)

LinearRegression()

In [55]:
y_pred = model.predict(X_test)

In [56]:
r2_score(y_test,y_pred)

0.983564631554963

In [57]:
model.intercept_ # c - intercept

array([0.85301253])

In [58]:
model.coef_ # m - coefficient

array([[-0.0796929]])

In [59]:
x = (0.5 - model.intercept_) / model.coef_ # y = mx + c, y = 0.5 find x

In [60]:
x

array([[4.42966125]])

In [61]:
np.exp(x) # converting time in minutes

array([[83.90298982]])